apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: openproject
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openproject-sc
  resources:
    requests:
      storage: 20Gi