apiVersion: v1
kind: Service
metadata:
  name: openproject-service
  namespace: openproject
  labels:
    app: openproject
spec:
  selector:
    app: openproject
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
