apiVersion: v1
kind: Service
metadata:
  name: memcached-svc
  namespace: openproject
spec:
  ports:
    - name: memcached
      port: 11211
      targetPort: 11211
      protocol: TCP
  selector:
    app: memcached
  clusterIP: None