apiVersion: v1
kind: Service
metadata:
  name: openproject-svc
  namespace: openproject
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: openproject